export const novel_data = [
    {
        "id":1,
        "title":"第一卷epub",
        "url":"/ReadNovel/AaGe1.epub"
    },
    {
        "id":2,
        "title":"第二卷epub",
        "url":"/ReadNovel/AaGe2.epub"
    },
    {
        "id":3,
        "title":"第三卷epub",
        "url":"/ReadNovel/AaGe3.epub"
    },
    {
        "id":4,
        "title":"第四卷epub",
        "url":"/ReadNovel/AaGe4.epub"
    },
    {
        "id":5,
        "title":"第五卷epub",
        "url":"/ReadNovel/AaGe5.epub"
    },
    {
        "id":6,
        "title":"第六卷epub",
        "url":"/ReadNovel/AaGe6.epub"
    },
    {
        "id":7,
        "title":"第七卷epub",
        "url":"/ReadNovel/AaGe7.epub"
    },
]
