
import localFont from "next/font/local";
import "./globals.css";
import GlobalUserState from "../ThemeProvider"
import { Suspense } from "react"

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "zzz'html com",
  description: "Generated by create next app",
};

function SearchBarFallback() {
  return <h2>🌀 Loading...</h2>;
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalUserState>
          <Suspense fallback={<SearchBarFallback />}>
            {children}
          </Suspense>
        </GlobalUserState>
      </body>
    </html>
  );
}
